### ISSUE TITLE
Incorrect time zone

### ISSUE THREAD

**Issue by soustruh** [petrpatek/covid-cz#1]
Hi,
the time zone in the API is incorrect, the source reads
`Poslední aktualizace: 17. 3. 2020 v 8:00` in Prague time zone (GMT+1),
which is translated into
`"lastUpdatedAtSource": "2020-03-17T08:00:00.000Z",` (UTC),
which actually means
`2020-03-17 09:00:00` in GMT+1.

Could you please fix it? 😊

**Comment by petrpatek** [comment]
Thanks for the tip! It should be fixed in the latest data.
