### ISSUE TITLE
Wrong number of infected people reported

### ISSUE THREAD

**Issue by zoul** [petrpatek/covid-cz#2]
```
{
  "totalTested": 15584,
  "infected": 1,
  "recovered": 6,
```

I guess this is caused by the number going over one thousand?

**Comment by geekmoss** [comment]
Number formatting is likely to be a problem. 
`1 000`

Yep, I see a pull request already exists. Great.

**Comment by petrpatek** [comment]
Fixed. closing in favor of #3. Thanks! :)
