### ISSUE TITLE
Feature request: hospitalizations

### ISSUE THREAD

**Issue by mormegil-cz** [petrpatek/covid-cz#6]
Could we get the numbers of hospitalizations from Section 4 of the MZCR website? IIANM these are not (yet?) available in the open data set. Thanks!

**Comment by petrpatek** [comment]
Sure! I will add that.

**Comment by petrpatek** [comment]
Added. You can find it here https://api.apify.com/v2/key-value-stores/K373S4uCFR9W1K8ei/records/LATEST?disableRedirect=true under the `hospitalizationData`.
