### ISSUE TITLE
New data overview request - MZČR

### ISSUE THREAD

**Issue by RoMeiRoCZE** [petrpatek/covid-cz#7]
Hello, The Ministry of Health updated data sheet. Could you add the following to the API:
https://onemocneni-aktualne.mzcr.cz/covid-19

To the main numbers +
- Current number of hospitalized patients with COVID ‑ 19 ("hospitalized")
- Current number of people with proven COVID ‑ 19 (without cures and deaths) ("activeCases")
+ somehow prepared from the table "hospitalizationData" - Current number of people in critical state ("critical")

ie. the final form
{
   "totalTested": ?,
   "infected": ?,
   "recovered": ?,
   "deceased": ?,
   "hospitalized": ?,
   "critical": ?,
   "activeCases": ?,

-----

And, just like "infectedByRegion", do "deathsByRegion" because the death report was added.

-----

Děkuji moc,
Roman

**Comment by petrpatek** [comment]
Přidáno, díky za feedback.
